# -*- coding: utf-8 -*-
"""orchestrator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxCk2Ej80HpjWFLvE2Pes_wqVQDW281-
"""

# C++ kodunu derle (-O3 parametresi ile optimizasyonu açıyoruz, çok hızlanır)
!g++ -O3 solver2.cpp -o mysolver

# Çalıştırma izni ver
!chmod +x mysolver

print("✅ Derleme tamamlandı! 'mysolver' dosyası hazır.")

import subprocess
import re
import shutil
import os

# --- 1. Setup Paths & Copy Files ---
INPUT_SUB = '/content/submission.csv'
INPUT_BIN = '/content/mysolver'
WORKING_DIR = '/content/'

print("📂 Ortam hazırlanıyor...")

if os.path.exists(INPUT_SUB):

    print(f"✅ {INPUT_SUB} bulundu.")
else:
    print("❌ UYARI: submission.csv bulunamadı! Lütfen dosyalar kısmına yükle.")

# bbox3 dosyasına çalıştırma izni ver (Çok Önemli!)
if os.path.exists(INPUT_BIN):
    os.chmod(INPUT_BIN, 0o755)
    print("✅ mysolver için çalıştırma izni verildi.")
else:
    print("❌ HATA: mysolver dosyası bulunamadı! Lütfen dosyalar kısmına sürükle.")

import math
import pandas as pd
import numpy as np
from numba import njit

@njit
def make_polygon_template():
    tw=0.15; th=0.2; bw=0.7; mw=0.4; ow=0.25
    tip=0.8; t1=0.5; t2=0.25; base=0.0; tbot=-th
    x=np.array([0,ow/2,ow/4,mw/2,mw/4,bw/2,tw/2,tw/2,-tw/2,-tw/2,-bw/2,-mw/4,-mw/2,-ow/4,-ow/2],np.float64)
    y=np.array([tip,t1,t1,t2,t2,base,base,tbot,tbot,base,base,t2,t2,t1,t1],np.float64)
    return x,y

@njit
def score_group(xs,ys,degs,tx,ty):
    n=xs.size; V=tx.size
    mnx=1e300; mny=1e300; mxx=-1e300; mxy=-1e300
    for i in range(n):
        r=degs[i]*math.pi/180.0
        c=math.cos(r); s=math.sin(r)
        xi=xs[i]; yi=ys[i]
        for j in range(V):
            X=c*tx[j]-s*ty[j]+xi
            Y=s*tx[j]+c*ty[j]+yi
            if X<mnx: mnx=X
            if X>mxx: mxx=X
            if Y<mny: mny=Y
            if Y>mxy: mxy=Y
    side=max(mxx-mnx,mxy-mny)
    return side*side/ n

def strip(a):
    return np.array([float(str(v).replace("s","")) for v in a],np.float64)

def all_csv_files():
    out=[]
    for f in subs:
        out += glob.glob(f + "/*.csv", recursive=False)
    return out

from decimal import Decimal, getcontext

from shapely import affinity
from shapely.geometry import Polygon

# Set precision for Decimal
getcontext().prec = 25
scale_factor = Decimal("1e18")

class ChristmasTree:
    """Represents a single, rotatable Christmas tree of a fixed size."""

    def __init__(self, center_x="0", center_y="0", angle="0"):
        """Initializes the Christmas tree with a specific position and rotation."""
        self.center_x = Decimal(center_x)
        self.center_y = Decimal(center_y)
        self.angle = Decimal(angle)

        trunk_w = Decimal("0.15")
        trunk_h = Decimal("0.2")
        base_w = Decimal("0.7")
        mid_w = Decimal("0.4")
        top_w = Decimal("0.25")
        tip_y = Decimal("0.8")
        tier_1_y = Decimal("0.5")
        tier_2_y = Decimal("0.25")
        base_y = Decimal("0.0")
        trunk_bottom_y = -trunk_h

        initial_polygon = Polygon(
            [
                # Start at Tip
                (Decimal("0.0") * scale_factor, tip_y * scale_factor),
                # Right side - Top Tier
                (top_w / Decimal("2") * scale_factor, tier_1_y * scale_factor),
                (top_w / Decimal("4") * scale_factor, tier_1_y * scale_factor),
                # Right side - Middle Tier
                (mid_w / Decimal("2") * scale_factor, tier_2_y * scale_factor),
                (mid_w / Decimal("4") * scale_factor, tier_2_y * scale_factor),
                # Right side - Bottom Tier
                (base_w / Decimal("2") * scale_factor, base_y * scale_factor),
                # Right Trunk
                (trunk_w / Decimal("2") * scale_factor, base_y * scale_factor),
                (trunk_w / Decimal("2") * scale_factor, trunk_bottom_y * scale_factor),
                # Left Trunk
                (-(trunk_w / Decimal("2")) * scale_factor, trunk_bottom_y * scale_factor),
                (-(trunk_w / Decimal("2")) * scale_factor, base_y * scale_factor),
                # Left side - Bottom Tier
                (-(base_w / Decimal("2")) * scale_factor, base_y * scale_factor),
                # Left side - Middle Tier
                (-(mid_w / Decimal("4")) * scale_factor, tier_2_y * scale_factor),
                (-(mid_w / Decimal("2")) * scale_factor, tier_2_y * scale_factor),
                # Left side - Top Tier
                (-(top_w / Decimal("4")) * scale_factor, tier_1_y * scale_factor),
                (-(top_w / Decimal("2")) * scale_factor, tier_1_y * scale_factor),
            ]
        )
        rotated = affinity.rotate(initial_polygon, float(self.angle), origin=(0, 0))
        self.polygon = affinity.translate(
            rotated, xoff=float(self.center_x * scale_factor), yoff=float(self.center_y * scale_factor)
        )

import pandas as pd
import numpy as np
from decimal import Decimal
from shapely.strtree import STRtree


def to_str(x: Decimal):
    return f"s{float(x)}"


def load_configuration_from_df(n, existing_df):
    """
    Load existing configuration from submission CSV.
    """
    group_data = existing_df[existing_df["id"].str.startswith(f"{n:03d}_")]
    trees = []
    for _, row in group_data.iterrows():
        x = row["x"][1:]  # Remove 's' prefix
        y = row["y"][1:]
        deg = row["deg"][1:]
        trees.append(ChristmasTree(x, y, deg))
    return trees

def get_score(trees, n=None):
    xys = np.concatenate([np.asarray(t.polygon.exterior.xy).T / 1e18 for t in trees])
    min_x, min_y = xys.min(axis=0)
    max_x, max_y = xys.max(axis=0)
    score = max(max_x - min_x, max_y - min_y) ** 2
    if n is not None:
        score /= n
    return score

def has_overlap(trees):
    """Check if any trees overlap"""
    if len(trees) <= 1:
        return False

    polygons = [t.polygon for t in trees]
    tree_index = STRtree(polygons)

    for i, poly in enumerate(polygons):
        indices = tree_index.query(poly)
        for idx in indices:
            if idx == i:
                continue
            if poly.intersects(polygons[idx]) and not poly.touches(polygons[idx]):
                return True
    return False

import pandas as pd

def eval_df_sub(df, verb):
    failed = []
    total_score = 0.0
    for n in range(1, 201):
        trees = load_configuration_from_df(n, df)
        score = get_score(trees, n)
        total_score += score
        if verb:
            print(f"{n:3}  {score:.6f}")
        if has_overlap(trees):
            failed.append(n)

    if len(failed) == 0:
        print("Overlap check was succesfull")
    else:
        print("Overlap check failed for", *failed)

    print(f"Total score: {total_score:.12f}")
    return total_score

def main():
    # Read in current ensemble output and check for overlaps
    df = pd.read_csv("submission.csv")
    initial_score = eval_df_sub(df, False)
    new_score = initial_score

    print("Starting mysolver runs")

    import subprocess
    import random

    while new_score == initial_score:
        random.seed() # Use a random seed every time; add fixed number for repeatability
        n =  str(random.randint(1,200))
        r = str(random.randint(10,1000))
        print(f"#### Running mysolver for n={n} r={r}")
        subprocess.run(["/content/mysolver",
                        "-n", n,
                        "-r", r])
        df = pd.read_csv("submission.csv")
        new_score = eval_df_sub(df, False)

main()